### ISSUE TITLE
Chat stops and Click to scroll window appear

### ISSUE THREAD

**Issue by keyoy** [Xzensi/NipahTV#128] opened 2024-09-12 18:16 UTC
After some time chats stops when doing nothing, not even moving mouse.  Every few secons. Unusable

**Comment by Xzensi** [comment] 2024-09-12 19:20
Thats a known issue indeed, I'm trying to fix that right now. Thanks for letting me know though!

Duplicate of #122

**Closed by Xzensi** 2024-09-12 19:20 UTC
