### ISSUE TITLE
[BUG] Page crashes when pressing an emote on Emote Holder with "Show quick emote holder" DISABLED

### ISSUE THREAD

**Issue by phere-x** [Xzensi/NipahTV#136] opened 2024-09-13 20:55 UTC
Browser: `Firefox 130.0 (64-bit)`

 ---

Enabling the "Show quick emote holder" option hides the default kick one & shows no emotes unless "Show Favorites" is enabled too. 

Disabling it entirely brings the default Kick one back but on pressing any emote it crashes the site (both on/off 'Send emotes to chat immediately on click')

**Comment by Xzensi** [comment] 2024-09-13 21:14
NTV has 2 features on the quick emote holder, it shows both recently used emotes which are your most used emotes, and those you manually favorited. But you do need to start sending emotes to populate the recently used emotes. It is indeed intended to completely replace the native Kick quick emotes holder because it sucks anyway.

Did you try sending emotes and it doesnt add them to the quick emote holder?

**Comment by phere-x** [comment] 2024-09-13 21:35
My native kick QEH was already populated with emotes. I used the emote menu to send new emotes thinking maybe it would refresh & poplulate it again but no change to the list.

Seems it breaks only on jackdoherty & xqc's channel, but it works fine on Buddha. Wondering what could be the difference I checked some others & they too worked fine until I tried Fousey's. Seems the correlation is Slow Mode being enabled (can't find others with it enabled to further test).

**Comment by Xzensi** [comment] 2024-09-13 21:43
I noticed that too, it seems to crash a lot especially when sending replies in xQc's chat, which it rarely does in other channels. I haven't figured out what it is yet. I've still got a lot of stability issues to fix with the new Kick website, but it sure is a pain to work with now. Please do let me know if you find out more useful or new information regarding to this.

**Comment by Xzensi** [comment] 2024-09-18 12:25
Since fixing #126 I have no longer been able to reproduce any of the page crashing issues, so I believe it was related and should be fixed now. If you experience any page crashing like this again please do let me know so I can look into it again.

**Closed by Xzensi** 2024-09-18 12:25 UTC
Labels: bug, P2
